In [14]:
import import_hack
import steps
from data_store import sqlite_table_datastore as sqlds
from data_store import sqlite_table_one_to_many_datastore as sqlotmds
from data_store import stream_ndarray_adapter_datastore as snads
from data_store import numpy_datastore as npds
from search import exhaustive_searcher as exs
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
productsiftbincount_sqlite_db_path='ds_data\imgid_productsiftbincount'
productsiftbincount_sqlite_table_name='imgid_productsiftbincount'

In [17]:
productsiftbincount_ds = sqlds.SQLiteTableDataStore(productsiftbincount_sqlite_db_path, productsiftbincount_sqlite_table_name)
np_neighbor_ids_ds=npds.NumpyDataStore()

In [18]:
with productsiftbincount_ds:
    print(productsiftbincount_ds.get_count())
    items=productsiftbincount_ds.get_items_sorted_by_ids()
    print(next(items).shape)
    print(next(items).shape)

999
(600,)
(600,)


In [28]:
productsiftbincount_ndarray_ds = snads.StreamNdarrayAdapterDataStore(productsiftbincount_ds, detect_final_shape_by_first_elem=True)

In [32]:
print(productsiftbincount_ndarray_ds.get_count())
items=productsiftbincount_ndarray_ds.get_items_sorted_by_ids()
print(items.shape)

999
(999, 600)


In [33]:
exs_searcher=exs.ExhaustiveSearcher(productsiftbincount_ndarray_ds.get_items_sorted_by_ids(), productsiftbincount_ndarray_ds.get_ids_sorted())

In [44]:
steps.search_step(productsiftbincount_ds, exs_searcher, 6 , np_neighbor_ids_ds)

In [45]:
print(np_neighbor_ids_ds.get_count())
print(np_neighbor_ids_ds.get_items_sorted_by_ids().shape)
print(np_neighbor_ids_ds.get_items_sorted_by_ids())

999
(999, 6)
[[  1   2   8   3   4   5]
 [  2   3   5   8   1   6]
 [  3   2   6   8   5   1]
 ..., 
 [997 994 991 998 995 992]
 [998 991 995 994 992 997]
 [999 996 993 992  87 961]]
