In [14]:
import import_hack
import steps
from data_store import sqlite_table_datastore as sqlds
from data_store import sqlite_table_one_to_many_datastore as sqlotmds
from data_store import stream_ndarray_adapter_datastore as snads
from data_store import numpy_datastore as npds
from search import exhaustive_searcher as exs
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [46]:
productsiftbincount_sqlite_db_path='ds_data\imgid_productsiftbincount'
productsiftbincount_sqlite_table_name='imgid_productsiftbincount'

In [47]:
productsiftbincount_ds = sqlds.SQLiteTableDataStore(productsiftbincount_sqlite_db_path, productsiftbincount_sqlite_table_name)
np_neighbor_ids_ds=npds.NumpyDataStore()

In [48]:
with productsiftbincount_ds:
    print(productsiftbincount_ds.get_count())
    items=productsiftbincount_ds.get_items_sorted_by_ids()
    print(next(items).shape)
    print(next(items).shape)

999
(600,)
(600,)


In [49]:
productsiftbincount_ndarray_ds = snads.StreamNdarrayAdapterDataStore(productsiftbincount_ds, detect_final_shape_by_first_elem=True)

In [50]:
print(productsiftbincount_ndarray_ds.get_count())
items=productsiftbincount_ndarray_ds.get_items_sorted_by_ids()
print(items.shape)

999
(999, 600)


In [51]:
exs_searcher=exs.ExhaustiveSearcher(productsiftbincount_ndarray_ds.get_items_sorted_by_ids(), productsiftbincount_ndarray_ds.get_ids_sorted())

In [52]:
steps.search_step(productsiftbincount_ds, exs_searcher, 6 , np_neighbor_ids_ds)

In [53]:
print(np_neighbor_ids_ds.get_count())
print(np_neighbor_ids_ds.get_items_sorted_by_ids().shape)
print(np_neighbor_ids_ds.get_items_sorted_by_ids())

999
(999, 6)
[[  1   2   8   3   4   5]
 [  2   3   5   8   1   6]
 [  3   2   6   8   5   1]
 ..., 
 [997 994 991 998 995 992]
 [998 991 995 994 992 997]
 [999 996 993 992  87 961]]


In [55]:
for i, neighbor_ids in enumerate(np_neighbor_ids_ds.get_items_sorted_by_ids()):
    print(i, neighbor_ids)

0 [1 2 8 3 4 5]
1 [2 3 5 8 1 6]
2 [3 2 6 8 5 1]
3 [  4   7   8   5 395 855]
4 [5 8 4 3 2 6]
5 [6 3 9 2 5 8]
6 [  7   4   8 855 395 371]
7 [8 4 5 7 3 2]
8 [9 6 2 3 5 8]
9 [ 10 555 550 558  61 551]
10 [11 18 14 13 15 16]
11 [ 12  14  15  18  17 160]
12 [ 13  10  62  63 553 555]
13 [14 17 11 13 18 10]
14 [ 15  11  18  17  14 240]
15 [ 16 555 552  10 530 554]
16 [ 17  14  18 630 540  13]
17 [18 13 11 17 14 16]
18 [19 22 25 27 24 21]
19 [20 23 26 21 24 27]
20 [21 24 22 20 23 27]
21 [22 24 27 19 21 25]
22 [23 26 20 21 24 27]
23 [24 27 22 19 21 25]
24 [25 27 19 24 22 83]
25 [ 26  23  20  21  24 183]
26 [27 24 22 25 19 23]
27 [ 28  35  31 207  34 205]
28 [29 33 32 36 34 30]
29 [30 36 33 32 35 29]
30 [31 35 32 34 28 29]
31 [32 29 30 36 35 33]
32 [33 36 29 30 35 32]
33 [ 34  29  35  31  30 201]
34 [35 36 31 33 30 32]
35 [36 33 30 29 35 32]
36 [37 41 16 43 63 40]
37 [ 38  41  45  42 194  44]
38 [ 39  42  38  44 231 112]
39 [ 40  41  38 513  45  37]
40 [ 41  43  38 194  40  37]
41 [ 42  38  43  39